### ISSUE TITLE
Quick duplicating all keys to new frame

### ISSUE THREAD

**Issue by nekrasovdmitriy** [Pullusb/storytools#42]
Suggestion — one button creating new frame with all keys duplicated from existing frame (like it is done in Storyboarder — "duplicate board").
It is useful because as usual you have to add local edits in existing frame, not changing everything. Now i have to manually selecting all frames and shift-D + dragging in Dope Sheet, frustrating.

**Comment by Pullusb** [comment]
Hi, thank you for the feedback.

If you always want to keep previous frames drawing, you can toggle the `additive draw`

![image](https://github.com/user-attachments/assets/cabcc589-bf68-4958-a181-eb6831b708ed)

But I agree having dedicated _single_  direct actions would be nice, instead of the `check/uncheck -> then act` workflow.

I wanted to implement an "Add GP key" button anyway (see #31) guess I should add a pair of two buttons instead.

**Comment by Pullusb** [comment]
Hello @nekrasovdmitriy,

"New GP frame" buttons have been freshly added in version 1.17.0
First button create empty keys, second duplicate previous, Ctrl + Click offset following keys.
More details in changelog below

![image](https://github.com/user-attachments/assets/9d258e43-a94a-4e3c-b890-ed2091afbbae)

Closing the issue. If you have further suggestions or found a bug, feel free to reopen here or create a new issue if it seems more appropriate


**1.17.0 changelog :**

added: Extend the control bar with new Grease pencil operators buttons:
 - `New GP frame` : Create new empty GP frame at position. jump forward if a frame exists at cursor. Ctrl + Click apply offset to all subsequent editable frames
 - `New GP frame copy` : Same behavior but copy content of currently active frame
 
added: addon preferences `Default Autolock Layers` set autolock state on new Grease pencils (enabled by default)  
added: addon preferences `Default Layer Use Light` to set Use light state on new created object (disabled by default)  
added: addon preferences `Grease Pencil Frame Offset` interval when offsetting key at creation (if already on a key) or when applying offset to subsequent frames

**Comment by nekrasovdmitriy** [comment]
Big thanks! I will test the update

**Comment by nekrasovdmitriy** [comment]
Strange thing is that both buttons add 12 extra frames to each new key. Keying each frame is more logical, or add frames offset in settings.

![Снимок экрана 2024-09-27 в 23 32 45](https://github.com/user-attachments/assets/a6334542-90bf-4c9c-828e-eff4acf2d060)

**Comment by Pullusb** [comment]
Hi.
Yes, both buttons work the same way, just a choice: `empty frame` or `copy frame`.

The offset is intentional, and happen only if your cursor is on a key (on unlocked and visible layers).
The frame offset setting exists, it's in addon-preferences for now. Maybe I'll add a more direct access to settings like this one, but not my priority ATM.
About the offset size, I've seen that storyboard people typically use larger spacing, so I went with a default offset value of `12`. You think it should be at `1` by default ?

Anyway, I will wait to have feedbacks after tests from multiple storyboard artists on this before changing anything.

**Comment by nekrasovdmitriy** [comment]
It is pretty frustrating to have different behaviour with cursor staying over current keyframe and not. 

Typical workflow: drawing on current frame, ONE KEY PRESS and continue drawing on new clean frame with onion skin or ONE KEY PRESS and continue editing current frame duplicate. (this is how it works in Storyboarder). 
Now i have to press RIGHT to step one frame forward and only there press empty frame or copy frame if i do not need an offset. 

Why offset is not handy? — when you boarding a movement wit a lot of keys, you have to jump between frames to check it, just pressing LEFT or RIGHT arrow. If you have in-betweens keys everywhere as default, it is not possible.

**Comment by Pullusb** [comment]
> It is pretty frustrating to have different behaviour with cursor staying over current keyframe and not.

If you don't have an "on-key" specific behavior, Then you'll **always** have to press `Right` then `add key`.

So, just to be sure about the behavior you expect.
If you set the `frame offset` in preference to `1` as mentioned in my previous message, is it not exactly as you want ?

![prefs](https://github.com/user-attachments/assets/70fd9b0a-35db-41cc-8a04-ff63b9909089)

**Comment by nekrasovdmitriy** [comment]
Yes, setting offset in preferences is handy, thanks.
