### ISSUE TITLE
Auto turning off Autolock Inactive Layers for creating keys

### ISSUE THREAD

**Issue by nekrasovdmitriy** [Pullusb/storytools#54]
Problem — it is handy to use **autolock grease pencil layers** for better erasing 'per tool', but it prevents using  **new Grease pencil empty frame** and **Duplicate current grease pencil frame** buttons. Locked layers are not keyed, so you have to manually turn autolock OFF every time you need to use buttons.

It is possible to automatically turn autolock OFF on button press and after creating new frame луны turning it ON?

**Comment by Pullusb** [comment]
Hi, it is possible, yes. I totally get your problem and I actually already planned to add an option to enable this behavior.

You can see this in issue #52 (look at "Layer target to add new keys" section).

Keying on locked layer will probably not be the default setting, as users will expect their locked layer to stay untouched.
But you will be able to choose.

Note: There will be a pause on the storytools development for the next 1 or 2 weeks, but after that I'll quickly get to this feature.

**Comment by nekrasovdmitriy** [comment]
Thanks for reply, will be looking forward for updates.

**Comment by Pullusb** [comment]
#52 has landed

![image](https://github.com/user-attachments/assets/84921741-b74a-4217-9002-e6341a00c7b7)

There is now a new gear icon that pop up a customization menu near GP gizmos

In this menu, you can change the behavior of `add frame` and `jump frame` buttons.
This allows to change frame offset, targeted layers, key type to jump on, etc...
In your case, what you'll find interesting is changing layer target to `visible` instead of default `accessible`.

Note that those properties are now local to scenes.
There is a separate tab in preferences listing these properties at user preference level.

`Sync mode` at the bottom define the behavior (per scene).
By default, preference reset local setting upon file opening and settings are shared between scene (propagated on change).
You can also choose to ignore preference on opening, or completely isolate those on a single scene.

The sync was hard to implement and maybe not that useful... It would probably have been better to just expose preference settings without any local scene properties.
But I thought it would be good to have settings not affected by preferences on some file (using "no sync"), not sure... Well, it's done.
Let me know what you think while experimenting.

Closing this issue.
If you encounter problems or have suggestion on this. Reopen issue #52 to discuss it (current issue was a duplicate)
